server.port=8080
server.address=0.0.0.0
spring.application.name=notesSharingApp
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update


# Connection Setting
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

spring.mail.username=${EMAIL}
spring.mail.password=${MAIL_PASSWORD}


spring.jwt.secret.key = ${JWT_KEY}
spring.JWT_EXPIRATION_TIME = ${JWT_EXPIRATION}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

#cloudinary.cloud_name=${CLOUDINARY_NAME}
#cloudinary.api_key=${CLOUDINARY_API_KEY}
#cloudinary.api_secret=${CLOUDINARY_API_SECRET}

cloud.aws.credentials.access-key=${aws_credentials_access_key}
cloud.aws.credentials.secret-key=${aws_credentials_secret_key}
cloud.aws.static.region=${aws_s3_region}
cloud.aws.bucketName=${aws_bucketName}