spring.application.name=notesSharingApp
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/notessharingapp
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.mail.username=khatridev318@gmail.com
spring.mail.password=otuy qxou kxyu llsw


spring.jwt.secret.key = 710e5e2272eb7de05c53191ffea2d2119e14cc413c1b736eea2fd688155a1b4b
spring.JWT_EXPIRATION_TIME = 600000


spring.servlet.multipart.enabled=true
