# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - NoteSharingApp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: windows-latest
    env:
      DB_URL: jdbc:mysql://127.0.0.1:3306/NotesSharingWebApp
      DB_USERNAME: root
      DB_PASSWORD: root123
      EMAIL: khatridev318@gmail.com
      MAIL_PASSWORD: scic aayf nmxe ajbc
      JWT_KEY: 710e5e2272eb7de05c53191ffea2d2119e14cc413c1b736eea2fd688155a1b4b
      JWT_EXPIRATION: 600000
      CLOUDINARY_NAME: dqd4booas
      CLOUDINARY_API_SECRET: c4ZfbdNHXPjZd71YXyd3haKholI
      CLOUDINARY_API_KEY: 948389993151134
    
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D9375F7BE4704AAE9EF250FE0C3C461F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_342665AFE7404091B465C38788548653 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FCE59CEC32EE477EBB7335E65339E7B7 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'NoteSharingApp'
          slot-name: 'Production'
          package: '*.jar'

          

